# Generated by Django 4.1.1 on 2022-10-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Delivery Charges'),
        ),
    ]
