# Generated by Django 4.1.1 on 2022-10-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_delivery_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Delivery Charges'),
        ),
    ]
