# Generated by Django 4.1.1 on 2022-10-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattribute",
            name="vendor_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Vendor Price",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Selling Price",
            ),
        ),
    ]
