# Generated by Django 4.1.1 on 2022-10-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_productattribute_vendor_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("priority", models.PositiveIntegerField(unique=True)),
                ("offer_percentage", models.PositiveIntegerField()),
                ("max_offer_price", models.PositiveBigIntegerField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("category", models.ManyToManyField(to="shop.category")),
                ("products", models.ManyToManyField(to="shop.product")),
            ],
        ),
    ]
