# Generated by Django 4.1.1 on 2022-09-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_author_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='brand', to='shop.brandname'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
