# Generated by Django 4.1.1 on 2022-10-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_offers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offers",
            options={
                "ordering": ["-priority"],
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
            },
        ),
        migrations.RemoveField(
            model_name="offers",
            name="max_offer_price",
        ),
        migrations.AddField(
            model_name="offers",
            name="max_offer_reduction",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="max reduction amount",
            ),
        ),
        migrations.AlterField(
            model_name="offers",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Offer Name"),
        ),
    ]
