# Generated by Django 4.1.1 on 2022-09-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_category_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='image',
            field=models.ImageField(default='images/default-image.jpg', upload_to='product_type_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default-image.jpg', upload_to='product_images/'),
        ),
    ]
