# Generated by Django 4.1.1 on 2022-09-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_producttype_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='image',
            field=models.ImageField(blank=True, default='images/default-image.jpg', upload_to='product_type_images/'),
        ),
    ]
