# Generated by Django 4.1.1 on 2022-10-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_offers_category_alter_offers_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offers",
            name="category",
            field=models.ManyToManyField(blank=True, to="shop.category"),
        ),
        migrations.AlterField(
            model_name="offers",
            name="products",
            field=models.ManyToManyField(blank=True, to="shop.product"),
        ),
    ]
