# Generated by Django 4.1.1 on 2022-10-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productreview_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
