# Generated by Django 4.1.1 on 2022-10-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_offers_category_alter_offers_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offers",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="offers",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
