# Generated by Django 4.1.1 on 2022-09-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default-image.jpg', upload_to='product_images/'),
        ),
    ]
