# Generated by Django 4.1.1 on 2022-10-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_offers_end_date_alter_offers_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="is_mobile",
            field=models.BooleanField(default=False),
        ),
    ]
