# Generated by Django 4.1.1 on 2022-11-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_banner_is_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="product_images/"),
        ),
    ]
