# Generated by Django 4.1.1 on 2022-11-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="images/default-image.jpg", upload_to="product_images/"
            ),
        ),
    ]
