# Generated by Django 4.1.1 on 2022-10-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_product_is_active_alter_productattribute_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
