# Generated by Django 4.1.1 on 2022-10-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
