# Generated by Django 4.1.1 on 2022-09-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='admin', max_length=220),
        ),
    ]
