# Generated by Django 4.1.1 on 2022-10-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0004_alter_vendorprofile_profile_pic"),
        ("customers", "0002_alter_customerprofile_profile_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorProfiles",
            fields=[],
            options={
                "verbose_name": "Vendor Profile",
                "verbose_name_plural": "Vendor Profiles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vendors.vendorprofile",),
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={
                "verbose_name": "Normal User",
                "verbose_name_plural": "Normal Users",
            },
        ),
    ]
