# Generated by Django 4.1.1 on 2022-10-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0004_alter_vendorprofile_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="razorpay_id",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
