# Generated by Django 4.1.1 on 2022-10-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customerprofile_profile_pic"),
        ("shop", "0002_banner"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cart",
            new_name="Basket",
        ),
        migrations.RenameModel(
            old_name="CartItem",
            new_name="BasketItem",
        ),
        migrations.RenameField(
            model_name="basketitem",
            old_name="cart",
            new_name="basket",
        ),
    ]
