# Generated by Django 4.1.1 on 2022-10-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_rename_cart_basket_rename_cartitem_basketitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketitem",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="color_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="delivery_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="orginal_amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="basketitem",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
