# Generated by Django 4.1.1 on 2022-10-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_basketitem_color_basketitem_color_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basket",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="basketitem",
            name="product_num",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="basket",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterOrderWithRespectTo(
            name="basketitem",
            order_with_respect_to="basket",
        ),
    ]
