# Generated by Django 4.1.1 on 2022-10-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_basket_options_basketitem_product_num_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basketitem",
            name="product_num",
        ),
    ]
