# Generated by Django 4.1.1 on 2022-10-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='used_users',
            field=models.ManyToManyField(blank=True, related_name='used_coupon', to='customers.customerprofile'),
        ),
    ]
