# Generated by Django 4.1.1 on 2022-10-27 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="orderItem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.orderitem",
            ),
        ),
    ]
